export interface InventoryItem {
  id: string;
  variantId: string;
  sku: string;
  nameEn: string;
  nameBn: string;
  category: string;
  categorySlug: string;
  brand: string;
  unit: string;
  unitValue: number;
  masikPrice: number;
  mrp: number;
  purchaseCost: number;
  stockAvailable: number;
  physicalStock: number;
  reservedStock: number;
  batchNumber: string;
  status: 'Healthy' | 'Low Stock' | 'Critical';
  isPrivateLabel?: boolean;
}

export const DEFAULT_INVENTORY_PRODUCTS: InventoryItem[] = [
  // 1. Rice (চাল)
  {
    id: 'p-rice-1',
    variantId: 'v-rice-chashi-25k',
    sku: 'RICE-MINI-CHASHI-25K',
    nameEn: 'Chashi Premium Miniket Rice 25kg',
    nameBn: 'চাষী প্রিমিয়াম মিনিকেট চাল ২৫ কেজি',
    category: 'চাল ও ডাল',
    categorySlug: 'staples_rice',
    brand: 'Chashi',
    unit: 'KG',
    unitValue: 25,
    masikPrice: 1980,
    mrp: 2150,
    purchaseCost: 1820,
    stockAvailable: 358,
    physicalStock: 500,
    reservedStock: 142,
    batchNumber: 'BAT-260901',
    status: 'Healthy',
  },
  {
    id: 'p-rice-2',
    variantId: 'v-rice-mb-25k',
    sku: 'RICE-MINI-MB-25K',
    nameEn: 'Masher Essentials Miniket Rice 25kg',
    nameBn: 'মাসের বাজার এসেনশিয়ালস মিনিকেট চাল ২৫ কেজি',
    category: 'চাল ও ডাল',
    categorySlug: 'staples_rice',
    brand: 'Masher Bazar Essentials',
    unit: 'KG',
    unitValue: 25,
    masikPrice: 1890,
    mrp: 2100,
    purchaseCost: 1720,
    stockAvailable: 420,
    physicalStock: 550,
    reservedStock: 130,
    batchNumber: 'BAT-260905',
    status: 'Healthy',
    isPrivateLabel: true,
  },
  {
    id: 'p-rice-3',
    variantId: 'v-rice-nazir-25k',
    sku: 'RICE-NAZIR-TEER-25K',
    nameEn: 'Teer Premium Nazirshail 25kg',
    nameBn: 'তীর প্রিমিয়াম নাজিরশাইল ২৫ কেজি',
    category: 'চাল ও ডাল',
    categorySlug: 'staples_rice',
    brand: 'Teer',
    unit: 'KG',
    unitValue: 25,
    masikPrice: 2160,
    mrp: 2350,
    purchaseCost: 1990,
    stockAvailable: 210,
    physicalStock: 300,
    reservedStock: 90,
    batchNumber: 'BAT-260828',
    status: 'Healthy',
  },
  {
    id: 'p-rice-4',
    variantId: 'v-rice-chini-5k',
    sku: 'RICE-CHINI-CHASHI-5K',
    nameEn: 'Chashi Chinigura Aromatic Rice 5kg',
    nameBn: 'চাষী সুগন্ধি চিনিগুঁড়া চাল ৫ কেজি',
    category: 'চাল ও ডাল',
    categorySlug: 'staples_rice',
    brand: 'Chashi',
    unit: 'KG',
    unitValue: 5,
    masikPrice: 650,
    mrp: 720,
    purchaseCost: 590,
    stockAvailable: 140,
    physicalStock: 180,
    reservedStock: 40,
    batchNumber: 'BAT-260910',
    status: 'Healthy',
  },

  // 2. Edible Oil (তেল)
  {
    id: 'p-oil-1',
    variantId: 'v-oil-rup-5l',
    sku: 'OIL-SOYA-RUP-5L',
    nameEn: 'Rupchanda Fortified Soybean Oil 5L',
    nameBn: 'রূপচাঁদা ভোজ্য সয়াবিন তেল ৫ লিটার',
    category: 'তেল ও ঘি',
    categorySlug: 'cooking_oil',
    brand: 'Rupchanda',
    unit: 'LITER',
    unitValue: 5,
    masikPrice: 815,
    mrp: 860,
    purchaseCost: 760,
    stockAvailable: 340,
    physicalStock: 450,
    reservedStock: 110,
    batchNumber: 'BAT-260814',
    status: 'Healthy',
  },
  {
    id: 'p-oil-2',
    variantId: 'v-oil-teer-5l',
    sku: 'OIL-SOYA-TEER-5L',
    nameEn: 'Teer Pure Soybean Oil 5L',
    nameBn: 'তীর পিওর সয়াবিন তেল ৫ লিটার',
    category: 'তেল ও ঘি',
    categorySlug: 'cooking_oil',
    brand: 'Teer',
    unit: 'LITER',
    unitValue: 5,
    masikPrice: 795,
    mrp: 850,
    purchaseCost: 740,
    stockAvailable: 30,
    physicalStock: 85,
    reservedStock: 55,
    batchNumber: 'BAT-260720',
    status: 'Low Stock',
  },
  {
    id: 'p-oil-3',
    variantId: 'v-oil-mb-5l',
    sku: 'OIL-SOYA-MB-5L',
    nameEn: 'Masher Essentials Fortified Soybean Oil 5L',
    nameBn: 'মাসের বাজার এসেনশিয়ালস সয়াবিন তেল ৫ লিটার',
    category: 'তেল ও ঘি',
    categorySlug: 'cooking_oil',
    brand: 'Masher Bazar Essentials',
    unit: 'LITER',
    unitValue: 5,
    masikPrice: 775,
    mrp: 850,
    purchaseCost: 715,
    stockAvailable: 280,
    physicalStock: 350,
    reservedStock: 70,
    batchNumber: 'BAT-260902',
    status: 'Healthy',
    isPrivateLabel: true,
  },
  {
    id: 'p-oil-4',
    variantId: 'v-oil-mustard-2l',
    sku: 'OIL-MUST-RADH-2L',
    nameEn: 'Radhuni Pure Mustard Oil 2L',
    nameBn: 'রাঁধুনী খাঁটি সরিষার তেল ২ লিটার',
    category: 'তেল ও ঘি',
    categorySlug: 'cooking_oil',
    brand: 'Radhuni',
    unit: 'LITER',
    unitValue: 2,
    masikPrice: 440,
    mrp: 480,
    purchaseCost: 395,
    stockAvailable: 115,
    physicalStock: 150,
    reservedStock: 35,
    batchNumber: 'BAT-260818',
    status: 'Healthy',
  },

  // 3. Lentils & Pulses (ডাল)
  {
    id: 'p-dal-1',
    variantId: 'v-dal-aci-2k',
    sku: 'DAL-MASOOR-ACI-2K',
    nameEn: 'ACI Pure Desi Masoor Dal 2kg',
    nameBn: 'এসিআই পিওর দেশি মসুর ডাল ২ কেজি',
    category: 'চাল ও ডাল',
    categorySlug: 'staples_rice',
    brand: 'ACI Pure',
    unit: 'KG',
    unitValue: 2,
    masikPrice: 310,
    mrp: 340,
    purchaseCost: 280,
    stockAvailable: 190,
    physicalStock: 250,
    reservedStock: 60,
    batchNumber: 'BAT-260908',
    status: 'Healthy',
  },
  {
    id: 'p-dal-2',
    variantId: 'v-dal-teer-2k',
    sku: 'DAL-MUNG-TEER-2K',
    nameEn: 'Teer Sona Mung Dal 2kg',
    nameBn: 'তীর সোনা মুগ ডাল ২ কেজি',
    category: 'চাল ও ডাল',
    categorySlug: 'staples_rice',
    brand: 'Teer',
    unit: 'KG',
    unitValue: 2,
    masikPrice: 330,
    mrp: 360,
    purchaseCost: 295,
    stockAvailable: 110,
    physicalStock: 160,
    reservedStock: 50,
    batchNumber: 'BAT-260825',
    status: 'Healthy',
  },
  {
    id: 'p-dal-3',
    variantId: 'v-dal-mb-2k',
    sku: 'DAL-MASOOR-MB-2K',
    nameEn: 'Masher Essentials Premium Masoor Dal 2kg',
    nameBn: 'মাসের বাজার এসেনশিয়ালস মসুর ডাল ২ কেজি',
    category: 'চাল ও ডাল',
    categorySlug: 'staples_rice',
    brand: 'Masher Bazar Essentials',
    unit: 'KG',
    unitValue: 2,
    masikPrice: 285,
    mrp: 330,
    purchaseCost: 255,
    stockAvailable: 230,
    physicalStock: 300,
    reservedStock: 70,
    batchNumber: 'BAT-260912',
    status: 'Healthy',
    isPrivateLabel: true,
  },

  // 4. Flour & Atta (আটা ও ময়দা)
  {
    id: 'p-flour-1',
    variantId: 'v-flour-fresh-5k',
    sku: 'FLOUR-ATTA-FRESH-5K',
    nameEn: 'Fresh Whole Wheat Atta 5kg',
    nameBn: 'ফ্রেশ লাল গম আটা ৫ কেজি',
    category: 'আটা ও ময়দা',
    categorySlug: 'staples_flour',
    brand: 'Fresh',
    unit: 'KG',
    unitValue: 5,
    masikPrice: 295,
    mrp: 325,
    purchaseCost: 265,
    stockAvailable: 175,
    physicalStock: 240,
    reservedStock: 65,
    batchNumber: 'BAT-260907',
    status: 'Healthy',
  },
  {
    id: 'p-flour-2',
    variantId: 'v-flour-teer-5k',
    sku: 'FLOUR-ATTA-TEER-5K',
    nameEn: 'Teer Fortified Whole Wheat Atta 5kg',
    nameBn: 'তীর পুষ্টিসমৃদ্ধ লাল আটা ৫ কেজি',
    category: 'আটা ও ময়দা',
    categorySlug: 'staples_flour',
    brand: 'Teer',
    unit: 'KG',
    unitValue: 5,
    masikPrice: 290,
    mrp: 320,
    purchaseCost: 260,
    stockAvailable: 130,
    physicalStock: 190,
    reservedStock: 60,
    batchNumber: 'BAT-260904',
    status: 'Healthy',
  },
  {
    id: 'p-flour-3',
    variantId: 'v-flour-mb-5k',
    sku: 'FLOUR-ATTA-MB-5K',
    nameEn: 'Masher Essentials Brown Atta 5kg',
    nameBn: 'মাসের বাজার এসেনশিয়ালস লাল আটা ৫ কেজি',
    category: 'আটা ও ময়দা',
    categorySlug: 'staples_flour',
    brand: 'Masher Bazar Essentials',
    unit: 'KG',
    unitValue: 5,
    masikPrice: 270,
    mrp: 315,
    purchaseCost: 240,
    stockAvailable: 210,
    physicalStock: 280,
    reservedStock: 70,
    batchNumber: 'BAT-260911',
    status: 'Healthy',
    isPrivateLabel: true,
  },

  // 5. Produce: Potatoes & Onions (আলু ও পেঁয়াজ)
  {
    id: 'p-pot-1',
    variantId: 'v-potato-5k',
    sku: 'PROD-POTATO-5K',
    nameEn: 'Munshiganj Fresh Diamond Potato 5kg',
    nameBn: 'মুন্সীগঞ্জ ডায়মন্ড আলু ৫ কেজি ব্যাগ',
    category: 'তাজা আলু ও পেঁয়াজ',
    categorySlug: 'produce_potato',
    brand: 'Masher Bazar Agro',
    unit: 'KG',
    unitValue: 5,
    masikPrice: 230,
    mrp: 260,
    purchaseCost: 205,
    stockAvailable: 290,
    physicalStock: 400,
    reservedStock: 110,
    batchNumber: 'BAT-260920',
    status: 'Healthy',
  },
  {
    id: 'p-oni-1',
    variantId: 'v-onion-5k',
    sku: 'PROD-ONION-5K',
    nameEn: 'Pabna Desi Red Onion 5kg',
    nameBn: 'পাবনার দেশি লাল পেঁয়াজ ৫ কেজি ব্যাগ',
    category: 'তাজা আলু ও পেঁয়াজ',
    categorySlug: 'produce_onion',
    brand: 'Masher Bazar Agro',
    unit: 'KG',
    unitValue: 5,
    masikPrice: 395,
    mrp: 450,
    purchaseCost: 355,
    stockAvailable: 180,
    physicalStock: 260,
    reservedStock: 80,
    batchNumber: 'BAT-260921',
    status: 'Healthy',
  },

  // 6. Salt, Sugar & Spices (লবণ, চিনি ও মসলা)
  {
    id: 'p-salt-1',
    variantId: 'v-salt-aci-1k',
    sku: 'SALT-ACI-1K',
    nameEn: 'ACI Pure Vacuum Refined Salt 1kg',
    nameBn: 'এসিআই পিওর ভ্যাকিউম লবণ ১ কেজি',
    category: 'লবণ ও মসলা',
    categorySlug: 'cooking_salt',
    brand: 'ACI Pure',
    unit: 'KG',
    unitValue: 1,
    masikPrice: 38,
    mrp: 42,
    purchaseCost: 33,
    stockAvailable: 450,
    physicalStock: 600,
    reservedStock: 150,
    batchNumber: 'BAT-260901',
    status: 'Healthy',
  },
  {
    id: 'p-sug-1',
    variantId: 'v-sugar-fresh-2k',
    sku: 'SUGAR-FRESH-2K',
    nameEn: 'Fresh White Refined Sugar 2kg',
    nameBn: 'ফ্রেশ পরিশোধিত চিনি ২ কেজি',
    category: 'চিনি ও মসলা',
    categorySlug: 'grocery_sugar',
    brand: 'Fresh',
    unit: 'KG',
    unitValue: 2,
    masikPrice: 288,
    mrp: 310,
    purchaseCost: 265,
    stockAvailable: 195,
    physicalStock: 260,
    reservedStock: 65,
    batchNumber: 'BAT-260906',
    status: 'Healthy',
  },
  {
    id: 'p-spice-1',
    variantId: 'v-radhuni-spices',
    sku: 'SPICE-RADHUNI-COMBO',
    nameEn: 'Radhuni Spices Combo (Turmeric + Chili) 500g',
    nameBn: 'রাঁধুনী হলুদ ও মরিচ গুঁড়া ৫০০ গ্রাম প্যাক',
    category: 'মসলা',
    categorySlug: 'spices',
    brand: 'Radhuni',
    unit: 'PACK',
    unitValue: 1,
    masikPrice: 595,
    mrp: 640,
    purchaseCost: 535,
    stockAvailable: 140,
    physicalStock: 190,
    reservedStock: 50,
    batchNumber: 'BAT-260830',
    status: 'Healthy',
  },

  // 7. Cleaning & Hygiene (পরিচ্ছন্নতা ও যত্ন)
  {
    id: 'p-det-1',
    variantId: 'v-det-wheel-2k',
    sku: 'CLEAN-WHEEL-2K',
    nameEn: 'Wheel 2in1 Washing Powder 2kg',
    nameBn: 'হুইল ডিটারজেন্ট পাউডার ২ কেজি',
    category: 'পরিচ্ছন্নতা',
    categorySlug: 'cleaning_detergent',
    brand: 'Unilever Bangladesh',
    unit: 'KG',
    unitValue: 2,
    masikPrice: 330,
    mrp: 360,
    purchaseCost: 295,
    stockAvailable: 220,
    physicalStock: 300,
    reservedStock: 80,
    batchNumber: 'BAT-260812',
    status: 'Healthy',
  },
  {
    id: 'p-det-2',
    variantId: 'v-det-surf-2k',
    sku: 'CLEAN-SURF-2K',
    nameEn: 'Surf Excel Quick Wash 2kg',
    nameBn: 'সার্ফ এক্সেল কুইক ওয়াশ ২ কেজি',
    category: 'পরিচ্ছন্নতা',
    categorySlug: 'cleaning_detergent',
    brand: 'Unilever Bangladesh',
    unit: 'KG',
    unitValue: 2,
    masikPrice: 490,
    mrp: 540,
    purchaseCost: 440,
    stockAvailable: 95,
    physicalStock: 140,
    reservedStock: 45,
    batchNumber: 'BAT-260810',
    status: 'Healthy',
  },
  {
    id: 'p-soap-1',
    variantId: 'v-soap-lifebuoy-4p',
    sku: 'HYG-LIFEBUOY-4P',
    nameEn: 'Lifebuoy Total Soap Bar (4-Pack)',
    nameBn: 'লাইফবয় টোটাল সাবান ৪টি প্যাক',
    category: 'ব্যক্তিগত যত্ন',
    categorySlug: 'cleaning_soap',
    brand: 'Unilever Bangladesh',
    unit: 'PACK',
    unitValue: 4,
    masikPrice: 218,
    mrp: 240,
    purchaseCost: 195,
    stockAvailable: 180,
    physicalStock: 250,
    reservedStock: 70,
    batchNumber: 'BAT-260903',
    status: 'Healthy',
  },
  {
    id: 'p-tis-1',
    variantId: 'v-tissue-bash-4p',
    sku: 'TISSUE-BASH-4P',
    nameEn: 'Bashundhara Facial Tissue (4-Pack)',
    nameBn: 'বসুন্ধরা ফেসিয়াল টিস্যু ৪ প্যাক',
    category: 'গৃহস্থালী টিস্যু',
    categorySlug: 'household_tissue',
    brand: 'Bashundhara',
    unit: 'PACK',
    unitValue: 4,
    masikPrice: 250,
    mrp: 280,
    purchaseCost: 220,
    stockAvailable: 160,
    physicalStock: 220,
    reservedStock: 60,
    batchNumber: 'BAT-260822',
    status: 'Healthy',
  },
];
